-- AL-HAYAT Supabase Database Schema
-- Paste this script into the Supabase SQL Editor (https://supabase.com/dashboard/project/zhdqcobqpzbpheusckym/sql)

-- 1. DROP OLD TABLES (Optional/Cleanup)
-- DROP TABLE IF EXISTS reviews;
-- DROP TABLE IF EXISTS products;

-- 2. CREATE PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  desc TEXT NOT NULL,
  price TEXT NOT NULL,
  price_original TEXT NOT NULL,
  discount TEXT NOT NULL,
  badge TEXT,
  ingredients TEXT[] DEFAULT '{}'::TEXT[],
  benefit TEXT NOT NULL,
  img TEXT NOT NULL,
  suitable_for TEXT NOT NULL,
  tagline TEXT NOT NULL,
  detailed_ingredients JSONB DEFAULT '[]'::JSONB,
  detailed_benefits JSONB DEFAULT '[]'::JSONB,
  ritual JSONB DEFAULT '[]'::JSONB,
  featured BOOLEAN DEFAULT FALSE,
  stock_status TEXT DEFAULT 'in_stock',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. CREATE REVIEWS TABLE
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  location TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  date TEXT NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  product_name TEXT NOT NULL, -- Fallback / Denormalized name
  text TEXT NOT NULL,
  verified BOOLEAN DEFAULT TRUE,
  approved BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. CREATE CONTACT MESSAGES TABLE
CREATE TABLE IF NOT EXISTS contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;

-- 6. CREATE RLS POLICIES

-- Products Policies: Anyone can read/write/update to allow seeding
CREATE POLICY "Allow public read access to products" ON products
  FOR SELECT USING (true);

CREATE POLICY "Allow public write access to products" ON products
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update access to products" ON products
  FOR UPDATE USING (true);

-- Reviews Policies: Anyone can read approved reviews, anyone can submit a review
CREATE POLICY "Allow public read access to approved reviews" ON reviews
  FOR SELECT USING (approved = true);

CREATE POLICY "Allow public write access to reviews" ON reviews
  FOR INSERT WITH CHECK (true);

-- Contact Messages Policies: Only authenticated can read, anyone can insert
CREATE POLICY "Allow public insert to contact_messages" ON contact_messages
  FOR INSERT WITH CHECK (true);
